config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :markets do
    resources :bookings, only: %i[create]
  end
  resources :bookings, except: %i[create] do
    resources :messages, only: %i[index create]
  end

  resources :dashboard, only: %i[index]

  get "pages/howitworks", to: "pages#howitworks"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :booking
  validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @user = current_user
    @bookings = policy_scope(Booking).order(updated_at: :desc)
    @booking = Booking.find(params[:booking_id])
    @message_read = Message.where("booking_id = #{@booking.id} AND user_id != #{@user.id}")
    @message_read.each do |message|
      message.status = true
      message.save
    end
    @message = Message.new
    @messages = @booking.messages.order(:id)
  end

  def create
    @bookings = policy_scope(Booking).order(updated_at: :desc)
    @booking = Booking.find(params[:booking_id])
    @message = Message.new(message_params)
    @message.booking = @booking
    @message.user = current_user
    authorize @message
    if @message.save
      @booking.updated_at = @message.created_at
      @booking.save
      BookingChannel.broadcast_to(
        @booking,
        messages_partial: render_to_string(partial: "message", locals: { message: @message}),
        bookings_partial: render_to_string(partial: "bookings", locals: { bookings: @bookings})
      )

      redirect_to booking_messages_path(@booking)
    else
      render "messages/index"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/views/messages/_bookings.html.erb
<% bookings.each do |booking| %>
  <div class="message-preview" >
    <div class="message-image">
      <%= image_tag booking.market.image %>
    </div>
    <div>
      <div class="user-info">
        <% if current_user == booking.user  %>
        <div class="user"><%= link_to booking.market.user.first_name, booking_messages_path(booking.id) %></div>
        <% elsif current_user == booking.market.user %>
        <div class="user"><%= link_to booking.user.first_name, booking_messages_path(booking.id) %></div>
        <% end %>
        <div class="date"><%= booking.updated_at.strftime("%a %b %e at %l:%M%p") %></div>
      </div>
      <div class="message-title"> <%= booking.market.title %> </div>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<% if message.user == current_user %>
          <div id="chat-right">
            <div class="message-content"><%= message.content %></div>
            <br>
            <div class="user-info">
              <div class="user-name"><%= message.user.first_name %></div>
              <div class="message-time"><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></div>
            </div>
          </div>
        <% else %>

          <div id="chat-left">
            <div class="message-content"><%= message.content %></div>
            <br>
            <div class="user-info">
              <div class="message-time"><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></div>
              <div class="user-name"><%= message.user.first_name %></div>
            </div>
          </div>


        <% end %>

app/views/messages/index.html.erb
<%= render 'shared/header' %>
<div class= "container">
  <div class="messages-container">
    <div class="message-overview" id= "bookings-overview">
      <%= render 'bookings', bookings: @bookings %>
    </div>
    <div class="chat" >
      <div class="chat-title"><%= @booking.market.title %></div>
      <div class="messages"  id='messages'  data-booking-id="<%= @booking.id %>" >
        <% @messages.each do |message| %>
        <%= render 'message', message: message %>
        <br>
        <% end %>
      </div>

      <%= simple_form_for [ @booking, @message ], remote: true do |f| %>

        <%#= f.input :content, label: false, placeholder: "Start to chat!" %>
        <%#div class="handshake">
          <%= link_to booking_path(@booking), method: :patch do %>
            <%#i class="fas fa-hands-helping btn-solid-red"> Handshake</i>
          <% end %>
          <%#%= f.button :submit, class: 'btn-line-red'  %>
        <%#/div> %>

        <div>

        <div class="messages">
          <%= f.input :content, label: false, class:"message-input", placeholder: "Write your message here!" %>
        </div>
        <div class="handshake">
          <% if current_user == @booking.market.user && @booking.status == "pending" %>
           <%= link_to "Send Handshake", booking_path(@booking), class: "btn-solid-red-handshake", method: :patch %>
          <% elsif current_user == @booking.user && @booking.status == "pending" %>
            <p class="canceled"><strong>Awaiting Handshake </strong></p>
          <% elsif current_user == @booking.user && @booking.status == "requested"  %>
            <%= link_to "Accept Handshake", booking_path(@booking), class: "btn-solid-red-handshake", method: :patch %>
          <% elsif @booking.status == "confirmed" %>
            <%= link_to "Cancel Handshake", booking_path(@booking), class: "btn-solid-red-handshake", method: :patch %>
            <%= link_to "Go to video chat", "/rooms/4", class: "btn-solid-red-handshake"%>
          <% elsif @booking.status == "rejected"  %>
            <p class="canceled"><strong>Handshake canceled</strong></p>
            <%= link_to "Handshake", booking_path(@booking), class: "btn-solid-red-handshake", method: :patch %>
            <%= link_to "Delete Chat", booking_path(@booking), class: "btn-solid-red-handshake", method: :delete %>
          <% end %>


          <%= f.button :submit, "Send Message", class: 'btn-line-red'  %>
        </div>
        <div class="handshake-explenation">
           <p><strong>How the handshake works: </strong>If you both agree on the conditions the offer creator can handshake on the deal to mark it as set.</p>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="bottom"></div>