config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :markets do
    resources :bookings, only: %i[create]
  end
  resources :bookings, except: %i[create] do
    resources :messages, only: %i[index create]
  end

  resources :dashboard, only: %i[index]

  get "pages/howitworks", to: "pages#howitworks"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
  <div class="footer-content container">

      <div class="footer-section about">
        <h1>Matter Of Time</h1>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum ratione ducimus, repellendus quisquam vel at nemo odio delectus iure assumenda adipisci excepturi quibusdam obcaecati, reiciendis recusandae, totam iste expedita placeat?
        </p>
        <div class="contact">
          <span><i class="fas fa-phone"></i> &nbsp; +49 123-456-789</span>
          <span><i class="fas fa-envelope"></i> &nbsp; info@matteroftime.me</span>
        </div>
      </div>

      <div class="footer-section links">
        <div class="links-left">
          <p>TOP CATEGORIES</p>
            <ul>
                <li><%= link_to "Music", "#", class: "quick-links"%></li>
                <li><%= link_to "Animals", "#", class: "quick-links" %></li>
                <li><%= link_to "Education", "#", class: "quick-links" %></li>
                <li><%= link_to "Cooking & Baking", "#", class: "quick-links" %></li>
                <li><%= link_to "Sports", "#", class: "quick-links" %></li>
            </ul>
        </div>
        <div class="links-middle">
          <p>BROWSE</p>
            <ul>
                <li><%= link_to "New", "#", class: "quick-links"%></li>
                <li><%= link_to "Remote", "#", class: "quick-links" %></li>
                <li><%= link_to "Staff picks", "#", class: "quick-links" %></li>
                <li><%= link_to "Recommended", "#", class: "quick-links" %></li>
                <li><%= link_to "Top picks", "#", class: "quick-links" %></li>
            </ul>
        </div>
        <div class="links-right">
          <p>ABOUT</p>
            <ul>
                <li><%= link_to "About MOT", "#", class: "quick-links"%></li>
                <li><%= link_to "Contact", "#", class: "quick-links" %></li>
                <li><%= link_to "Career", "#", class: "quick-links" %></li>
                <li><%= link_to "Team", "#", class: "quick-links" %></li>
                <li><%= link_to "Learn more", "#", class: "quick-links" %></li>
            </ul>
        </div>
    </div>



</div>
  <div class="footer-bottom">
    <div>
      <%= link_to "Privacy Policy", "#", class: "bottom-links"%>
      <%= link_to "Terms of Use", "#", class: "bottom-links"%>
      <%= link_to "Contact Us", "#", class: "bottom-links"%>
    </div>

    <div class="socials">
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-youtube"></i></a>
    </div>
  </div>

app/views/shared/_header.html.erb
<div class="container">
  <h1 id='profile_header'>Profile</h1>
  <div id='profile_menu'>
    <%= link_to "Dashboard", "/dashboard", class: "nav-link hover" %>
    <%= link_to "Messages(#{current_user.unread_messages.count})", "/bookings", class: "nav-link hover" %>
    <%= link_to "Saved", "#", class: "nav-link hover" %>
    <%= link_to "Your Offers/Requests", "#", class: "nav-link hover" %>
    <%= link_to "Profile Settings", "#", class: "nav-link hover" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "MOT-logo.svg" %>
    <% end %>

    <div class="nav-list ">
      <%= link_to "Home", "/", class: "nav-link hover" %>
      <%= link_to "Browse", "/markets", class: "nav-link hover" %>
      <%= link_to "Categories", "#", class: "nav-link hover" %>
      <%= link_to "How it works", "/#howitworks", class: "nav-link hover" %>
    </div>


    <div class="collapse navbar-collapse collapse-style" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-list pr-2">

          </li>

          <% if @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else  %>

              <%= image_tag "#{@user.avatar}", class: "avatar dropdown-toggle login-img", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% if current_user.unread_messages.count > 0 %>
                <%= link_to "#{current_user.unread_messages.count}", "/bookings", class:"unread" %>
              <% end %>
            <% end %>
            <li class="nav-item dropdown login-dd">
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Create an offer", new_market_path, class: "dropdown-item" %>
                <%= link_to "Messages", "/bookings", class: "dropdown-item" %>
                <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn-line-red login" %>
          </li>
        <% end %>
        </div>
      </ul>
    </div>
  </div>
</div>