config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :markets do
    resources :bookings, only: %i[create]
  end
  resources :bookings, except: %i[create] do
    resources :messages, only: %i[index create]
  end

  resources :dashboard, only: %i[index]

  get "pages/howitworks", to: "pages#howitworks"
end

app/models/market.rb
class Market < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  enum offer_request: %i[offer request]
  validates :title, :category, :description, presence: true
  has_one_attached :photo
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :user, only: %i[index show new create]

  def index
    @markets = policy_scope(Market).order(created_at: :desc)
    #@markets = Market.all
    if params[:category].present? && params[:category] != ""

      sql_query = "category ILIKE :category"
      @markets = Market.where(sql_query, category: "%#{params[:category]}%")
    elsif
      params[:query].present?
      sql_query = "title ILIKE :query OR description ILIKE :query"
      @markets = Market.where(sql_query, query: "%#{params[:query]}%")
    else
      @markets = Market.all
    end
  end

  def new
    @market = Market.new
    authorize @market
  end

  def create
    @market = Market.new(market_params)
    authorize @market
    @market.user_id = current_user.id
    @market.offer_request = 0
    if @market.save
      redirect_to market_path(@market)
    else
      render :new
    end
  end

  def update
  end

  def show
    @market = Market.find(params[:id])
    authorize @market
    @booking = Booking.find_by(market: @market, user: current_user)
    respond_to do |format|
      format.html
      format.js
    end
  end


  private

  def user
    @user = current_user
  end

  def market_params
    params.require(:market).permit(:title, :category, :description, :photo)
  end
end

app/views/markets/_form.html.erb
<div class="container">
  <div class="login-signup">
    <div class="sign-up">
    <h2>Create your own offer</h2>

    <%= simple_form_for(@market) do |f| %>
      <div class="form-inputs">
        <%= f.input :title,
                    required: false,
                    autofocus: true,
                    input_html: { placeholder: "Write you title here" } %>
        <p><%= f.label :description %></p>
        <%= f.text_area :description,
                    class: "form-description",
                    required: false,
                    autofocus: true,
                    input_html: { placeholder: "Describe your offer here" } %>
        <%= f.input :category, collection: %w[Animals Music Plants Handywork Concerts Transportation Crafts Sports Education Circus Film&Photography Baking&Cooking] %>
        <%# <p><%= f.label :photo %></p>
        <%# <p><%= f.file_field :photo,  multiple: false, class: "d-none", direct_upload: true %></p>
        <%= f.input :photo,
          input_html: {
          class: "d-none",
          multiple: false,
          direct_upload: true
      }, label_html: { class: "upload-photo"}, label: "+ Attach photo" %>
        <%#<p><%= f.file_field :photo, multiple: false, direct_upload: true </p> %>
      </div>

      <div class="form-actions btn-solid-red offer-submit">
        <%#= link_to 'Create Offer', market_path(@market) %>
        <%= f.button :submit, "Create Offer" %>
      </div>
    <% end %>
      </div>
      <div class="form-image">
        <%= image_tag "master-of-time.png" %>
      </div>
   </div>
</div>

app/views/markets/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with url: market_bookings_path(market.id), local: true do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Your Message</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div >
            <%= form.text_area :message_text, class: "form-control", id: "message-text" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn-solid-red-message">Send Message</button>
          <%# <button type="button" class="btn-line-red" data-dismiss="modal">Close</button> %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/markets/index.html.erb
<div class="container">

  <h1 class="text-center">Overview</h1>

  <div class="index-top">
    <div class="search-form">
        <div class="search-input"><%= form_tag markets_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "What are you looking for?"%></div>
          <div><%= submit_tag "Search", class: "btn-line-red" %></div>
        <% end %>
    </div>
    <div class="filter">
        <div class="filter-dd"><%= form_tag markets_path, method: :get do %>
          <%= select_tag :category, options_for_select(['Choose category', 'Animals','Music','Plants', 'Handywork', 'Concerts', 'Transportation', 'Crafts', 'Sports', 'Education', 'Circus', 'Film & Photography', 'Baking & Cooking']) %></div>
        <div><%= submit_tag "Filter", class: "btn-line-red" %></div>
      <% end %>
    </div>
  </div>
  </div>


  <div class="img-right">
  <div class="container">
  <div class="index-cards">
    <% @markets.each do |market| %>

    <div class="card-trip">
    <%= link_to market_path(market) do %>
      <% if market.photo.attached? %>
        <%= cl_image_tag "#{market.photo.key}" %>
        <% else %>
        <%= image_tag "#{market.image}" %>
      <% end %>
    <% end  %>
      <div class="card-trip-infos">
        <div class="card-title">
          <div class="title-link"><%= link_to market.title, market_path(market) %></div>
          <%# <h3>60</h3> %>
        </div>
            <div>
              <i class="fas fa-heart card-trip-user"></i>
              <%# <p><%= market.description %></p>
            </div>
            <div class="center-btn"><%= button_to "See Details", market_path(market), :class => "btn-line-red card-btn", :method => :get %></div>
            <br>
          </div>


        </div>
    <% end  %>
  </div>
  </div>
  </div>
</div>

app/views/markets/new.html.erb
<%= render "form", market: @market %>

app/views/markets/show.html.erb
<div class="container">
  <div class="show-card">

    <div class="card-images">
      <div class="large-image">
      <% if @market.photo.attached? %>
        <%= cl_image_tag "#{@market.photo.key}" %>
      <% else %>
        <%= image_tag "#{@market.image}" %>
      <% end %>
      </div>
    </div>

    <div class="all-infos">
      <div id="like">
        <h2><%= @market.title %></h2>
        <div class="save-icon"><%= link_to "#" do %>
          <i class="fas fa-heart"></i>
        <% end %></div>
        <br>
      </div>
      <i class="fas fa-map-marker-alt short-info short-info-top"></i>  Friedrichstr. 31, 10732 Berlin <br>
      <i class="fas fa-clock short-info"></i>  60 Minutes<br>
      <i class="fas fa-user short-info"> </i>  <%= @market.user.first_name %> <%= @market.user.last_name %><br><br>

      <p><%= @market.description %></p>
      <div class="market-buttons">
        <!-- Button trigger modal -->
        <% if @booking.present? %>
          <div>
            <p id="message_info">You have already send a message.</p>
            <p><%= link_to "View your messages", booking_messages_path(@booking), class:"btn-line-red" %></p>
          </div>
        <% else %>
          <button type="button" class="btn-solid-red-message" data-toggle="modal" data-target="#exampleModal">
            Write a message
          </button>


        <%= render "markets/modal", market: @market, booking: @booking %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="headline">
    <h2 class= "">Other offers you might like</h2>
  </div>
    <div class="four-cards">
      <% markets = Market.limit(4).order("RANDOM()") %>
      <% markets.each do |market| %>
        <div class="card-trip">
          <%= image_tag "#{market.image}" %>
          <div class="card-trip-infos">
            <div class= "card-title">
              <div class="title-link"><%= link_to market.title, market_path(market) %></div>
            </div>
            <div>
              <i class="fas fa-heart card-trip-user"></i>
              <%# <p><%= market.description %></p>
            </div>
            <%= button_to "See Details", market_path(market), :class => "btn-line-red card-btn", :method => :get %>
            <br>
          </div>
        </div>
      <% end  %>
    </div>
</div>